apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-config
  namespace: sandipto-portfolio
data:
  QDRANT_URL: "http://qdrant-service:6333"
  AI_BACKEND_URL: "http://ai-backend-service:8000"
  NEXTAUTH_URL: "http://sandipto.in"
