name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          port: 7576
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            if [ ! -d "/home/deploy/_Portfolio_" ]; then
              echo "Portfolio directory not found. Cloning repository..."

              git clone https://github.com/sandipto729/_Portfolio_.git /home/deploy/_Portfolio_

              cd /home/deploy/_Portfolio_
            else
              echo "Portfolio directory exists. Updating code..."

              cd /home/deploy/_Portfolio_
              git pull origin main
            fi

            echo "Deploying Docker containers..."

            docker compose up -d --build
